apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    applicationsSync: create-update
  generators:
  - list:
      elements:
      - cluster: "my-cluster1"
        server: "https://kubernetes.default.svc"
        environment: "my-app-prod"
        git: https://github.com/bebosudo/argo-on-speck.git
      # - cluster: "my-cluster2"
      #   server: "https://my-control-plane-endpoint.example.com"
      #   environment: "my-app-qa"
      #   git: https://github.com/bebosudo/argo-on-speck.git
  template:
    metadata:
      name: "{{ .environment }}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      destination:
        server: "{{ .server }}"
        namespace: my-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
      source:
        repoURL: "{{ .git }}"
        targetRevision: main
        path: "manifests/hello-world/environments/{{ .cluster }}"
